### ISSUE TITLE
ListboxField not showing selected values

### ISSUE THREAD

**Issue by jasjitCheema** [silverstripe/silverstripe-widgets#182] opened 2020-01-18 19:52 UTC
Steps to follow:-
1. Create custom widget, in which "FieldList" is having "ListboxField"
2. Add widget in page and try to select multiple entries from ListboxField. After saving those selected values are gone. 

*Checked in Database and these values are getting saved in string form eg. ["45","50"]

Please let me know, if any idea

**Comment by robbieaverill** [comment] 2020-01-18 23:10
Would you mind sharing the code for your custom widget please?

**Comment by jasjitCheema** [comment] 2020-01-18 23:11
Yes! Sure

**Comment by jasjitCheema** [comment] 2020-01-18 23:12
May i know your skype?

**Comment by robbieaverill** [comment] 2020-01-18 23:17
I don't have Skype. If possible, you could remove any sensitive code from the file and post it here or in a GitHub Gist. If not, you can reach me on the Silverstripe Community Slack channel.

**Comment by jasjitCheema** [comment] 2020-01-18 23:19
Here is the come to create new Widget:-
```

<?php

namespace Widgets\NewsUpdates;


use SilverStripe\Widgets\Model\Widget;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\TextField;
use SilverStripe\Forms\TextareaField;
use SilverStripe\Forms\NumericField;
use SilverStripe\Forms\ListboxField;
use SilverStripe\ORM\ArrayList;
use SilverStripe\View\ArrayData;
use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
use SilverStripe\Forms\DropdownField;

use News\NewsDetailPage;


class NewsUpdates extends Widget{
	private static $db = array(
		'WidgetTitle' => 'Varchar',
		'NewsPagesId_A'		=>	'Text',
		'WidgetWidth'   =>  'Varchar',
		'ViewAll'		=>	'Varchar'
	);
	private static $title = 'NewsUpdates HALF';
	private static $cmsTitle = 'NewsUpdates';
	private static $description = 'Description goes here';

	private static $many_many = [
		//'NewsPagesId' => NewsDetailPage::class,
	];

	public function getCMSFields(){
		$news_detail = NewsDetailPage::get()->map('ID','Title')->toArray();
		//print_r( $news_detail );
		//print_r($this->NewsPagesId_A);exit;
		//$news_detail = array("1"=>"one","2"=>"two","3"=>"three");


		$f = new FieldList(
			new TextField('WidgetTitle', 'Title'),
			new TextField('ViewAll', 'View all link'),
			ListboxField::create('NewsPagesId_A','Select newsfff',$news_detail),
			DropdownField::create('WidgetWidth','Widget Width',[
				'12'    =>  'FULL',
				'6'     =>  'HALF',
				'4'     =>  '1/3'
			])
		);
		return $f;
		
	}
	
}
```

**Comment by jasjitCheema** [comment] 2020-01-18 23:20
> I don't have Skype. If possible, you could remove any sensitive code from the file and post it here or in a GitHub Gist. If not, you can reach me on the Silverstripe Community Slack channel.

Okay! Thanks for your response

**Comment by jasjitCheema** [comment] 2020-01-18 23:24
May i know how to username of Slack. I can give you credentials of the Website

**Comment by jasjitCheema** [comment] 2020-01-20 06:40
Any luck?

**Comment by jasjitCheema** [comment] 2020-02-26 09:22
Got my mistake. 
To fix this i have to use "many many" relationship.

```
private static $many_many = [
	'NewsPagesId' => NewsDetailPage::class,
];
```
Add following cms field:-

`ListboxField::create('NewsPagesId','Select news',$news_detail, **$this->NewsPagesId()** )`

**Comment by dhensby** [comment] 2020-04-06 10:03
closed as not a bug, then

**Closed as completed by dhensby** 2020-04-06 10:03 UTC
Labels: type/bug, impact/medium, affects/v4, complexity/low
